### PR TITLE
12.14.1 Offsets

### PR DESCRIPTION
**Pull request by Allan-Cao**
UNTESTED but based on https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-350.html

### CODE REVIEW

**Comment by Allan-Cao** [comment]
If someone could test these offsets or adjust them based on the forum post would appreciate it

**Comment by daisukedd** [comment]
how can i compile to .exe?

**Comment by JoanJuan10** [comment]
```[14-51-09] Outdated Offsets detected. Downloading new ones
[14-51-09] Fetching new offsets from https://raw.githubusercontent.com/Allan-Cao/LeagueBroadcast/patch-1/Offsets/Offsets-12.14.1.json
[14-51-09] New Client TaTDmDLNQ0CznXYLcPa9wg connected from http://localhost:9001
[14-51-09] Game Loaded
[14-51-09] Game Paused
[14-51-09] LiveEventAPI Connected
[14-51-09] Game Resumed
[14-51-10] Init Team data
[14-51-10] Init UI
[14-51-10] Sending game start key inputs
[14-51-10] [WARNING] Camille not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Sequence contains no matching element
[14-51-10] [WARNING] Viego not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Xerath not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Caitlyn not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Lux not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Cho'Gath not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Evelynn not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Viktor not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Varus not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Karma not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Camille not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Viego not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Xerath not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Caitlyn not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Lux not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Cho'Gath not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Evelynn not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Viktor not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Varus not found in memory snapshot. Values will be incorrect!
[14-51-10] [WARNING] Karma not found in memory snapshot. Values will be incorrect!
[14-51-11] [WARNING] Could not download https://raw.githubusercontent.com/Allan-Cao/LeagueBroadcast/patch-1/Offsets/Offsets-12.14.1.json: The operation has timed out.
[14-51-11] Received updated offsets
[14-51-11] New Offsets not yet online. Checking to make sure if new patch should already be used
[14-51-11] [WARNING] App Crash detected. Writing Crash report to CrashLogs\Crash-2022-07-29-14-51.log
```

Offsets doesn't seem to be correct

**Comment by JoanJuan10** [comment]
> how can i compile to .exe?

You only need to modify your config for it to aim to new offset repo.

**Comment by floh22** [comment]
Offsets updated

**Pull request closed without merging**
