### PR TITLE
Update Farsight for 64bit League

### PR DESCRIPTION
**Pull request by FFFFFFFXXXXXXX**
I updated the Farsight module to work with the new 64bit game client and added offsets for 13.7.1.

### CODE REVIEW

**Comment by floh22** [comment]
Looks good. One question, what is the rationale for introducing the level offset when level can be directly calculated from EXP? Seems like more maintanence work to me

**Comment by FFFFFFFXXXXXXX** [comment]
I assumed the level-from-exp calculation was because there was no offset for the level before the 64bit version (or i atleast didnt see one before).
If you prefer calculating it instead of getting it from the offset I can remove it?

**Comment by floh22** [comment]
It's fine, though as far as I can tell update code is missing to manage the file version change, which might break the program for those updating versions and would force a manual deletion of the config file. Have you tested this and it works anyway? I am currently not able to access an environment where I can test this myself.

It would be great if you could add the migration code or revert back to not using the offset, either works fine

**Comment by FFFFFFFXXXXXXX** [comment]
Im currently looking into migration code, since we atleast need the new NameLength offset (GameObject.Name is now a packed string).

**Comment by FFFFFFFXXXXXXX** [comment]
Alright, I think I got it. I incremented the FarsightConfig version to 3, which forces an update of the offsets.
It tested it on my local version. Does this work for all cases or did I miss something?

**Comment by floh22** [comment]
Looks good I think

**Comment by floh22** [comment]
I'll build and deploy tomorrow evening once I get access to my PC

**Pull request merged**
